In [1]:
import pandas as pd

In [7]:
import numpy as np

## Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1,6,3,15])

In [9]:
a[2]

np.int64(3)

In [10]:
a[2] = 7
a

array([ 1,  6,  7, 15])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.linspace(0,1,15)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

## Multi-dimesional arrays

In [16]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [22]:
n[0,1] = 25
n

array([[ 1, 25,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
n[1]

array([4, 5, 6])

In [25]:
n[:,1]

array([25,  5,  8])

## Randomly generated arrays

In [26]:
np.random.rand(5,2)

array([[0.05161355, 0.37892982],
       [0.98379252, 0.14146138],
       [0.94754361, 0.88462432],
       [0.76690924, 0.69150008],
       [0.36798246, 0.57479274]])

In [27]:
np.random.rand(5,2)*10

array([[9.31142725, 1.33665912],
       [3.40837181, 3.0220161 ],
       [7.76266746, 2.63249435],
       [4.42436598, 2.04232826],
       [4.23304067, 6.9176235 ]])

In [29]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [30]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [35]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
a+1

array([1, 2, 3, 4, 5])

In [41]:
b = (10 + (a/2))**2

In [42]:
a + b

array([100.  , 111.25, 123.  , 135.25, 148.  ])

## Comparison operations

In [43]:
a >= 2

array([False, False,  True,  True,  True])

In [44]:
a < b

array([ True,  True,  True,  True,  True])

In [45]:
a[  a > 2.5]

array([3, 4])

## Summarizing operations

In [46]:
a.min()

np.int64(0)

In [47]:
a.max()

np.int64(4)

In [48]:
a.sum()

np.int64(10)

In [49]:
a.mean()

np.float64(2.0)

In [50]:
a.std()

np.float64(1.4142135623730951)

In [51]:
n.sum()

np.int64(68)

In [52]:
n.std()

np.float64(6.6015336788946435)

## Multiplication

In [3]:
def vector_vector_multiplication(u, v): 
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n): 
        result = result + u[i] * v[i]

    return result

In [8]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [9]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [11]:
u.dot(v) #the formula already exists in numpy

np.int64(14)

In [15]:
U = np.array([[2,4,5,6], [1,2,1,2], [3,1,2,1]])

In [19]:
U[0][1]

np.int64(4)

In [20]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1]==v.shape[0]
    n = v.shape[0]
    m = U.shape[0] # nr of rows
    result = np.zeros(m)
    for j in range(m):
        result[j] = vector_vector_multiplication(U[j], v)
    return result

In [21]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [22]:
U.dot(v)

array([14,  5,  5])

In [23]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [24]:
def matrix_matrix_multiplication(U, V): 
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [25]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [26]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [27]:
I = np.eye(3)

In [31]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse 
Only square matrix have inverse matrix

In [32]:
Vs = V[[0,1,2]]

In [33]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [34]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [37]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])